import { BlogPost, Video, ChartEntry, Comment, Artist, TrendingTopic, Poll } from './types';

export const BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    slug: 'rise-of-afrobeats-global',
    title: 'The Unstoppable Rise of Afrobeats Globally',
    excerpt: 'How Nigerian and Ghanaian artists are taking over the world stage, from Grammy wins to sold-out stadium tours. We analyze the numbers behind the movement.',
    content: 'Afrobeats has transcended borders...',
    author: 'Chioma N.',
    date: 'Oct 12, 2023',
    imageUrl: 'https://picsum.photos/seed/afrobeats/800/600',
    category: 'Music',
    featured: true
  },
  {
    id: '2',
    slug: 'top-10-dance-challenges-2023',
    title: 'Top 10 Viral Dance Challenges of 2023',
    excerpt: 'From TikTok to the streets of Lagos, these represent the moves that defined the year. Did your favorite make the list?',
    content: 'Dance is the heartbeat of African entertainment...',
    author: 'David K.',
    date: 'Nov 05, 2023',
    imageUrl: 'https://picsum.photos/seed/dance/800/600',
    category: 'Culture'
  },
  {
    id: '3',
    slug: 'amapiano-sound-of-freedom',
    title: 'Amapiano: The Sound of Freedom',
    excerpt: 'Exploring the roots of the South African house music genre that has captivated the continent featuring exclusive DJ interviews.',
    content: 'Deep basslines and piano chords...',
    author: 'Sipho M.',
    date: 'Nov 20, 2023',
    imageUrl: 'https://picsum.photos/seed/amapiano/800/600',
    category: 'Music',
    featured: true
  },
  {
    id: '4',
    slug: 'fashion-week-lagos-recap',
    title: 'Lagos Fashion Week: A Recap',
    excerpt: 'The trends, the designers, and the looks that stole the show this season. A visual diary of African excellence.',
    content: 'Fashion in Africa is bold...',
    author: 'Zainab A.',
    date: 'Dec 01, 2023',
    imageUrl: 'https://picsum.photos/seed/fashion/800/600',
    category: 'Lifestyle'
  },
  {
    id: '5',
    slug: 'universal-music-africa-deal',
    title: 'Universal Music Group Expands African Operations',
    excerpt: 'A deep dive into the multimillion-dollar investment reshaping the continent\'s recording infrastructure and what it means for indie artists.',
    content: 'The major labels are here to stay...',
    author: 'Emeka O.',
    date: 'Dec 15, 2023',
    imageUrl: 'https://picsum.photos/seed/business1/800/600',
    category: 'Industry'
  },
  {
    id: '6',
    slug: 'spotify-streaming-report-2023',
    title: 'Spotify Africa Report: Streaming Numbers Double',
    excerpt: 'New data shows a 100% year-over-year growth in paid subscriptions across Sub-Saharan Africa. Here is the breakdown by region.',
    content: 'Data suggests a digital revolution...',
    author: 'Sarah J.',
    date: 'Dec 20, 2023',
    imageUrl: 'https://picsum.photos/seed/stats/800/600',
    category: 'Industry'
  },
  {
    id: '7',
    slug: 'afro-nation-portugal',
    title: 'Afro Nation Portugal: What to Expect',
    excerpt: 'The lineup, the vibes, and the travel tips you need for the world\'s biggest Afrobeats festival.',
    content: 'Summer is coming...',
    author: 'Sarah J.',
    date: 'Jan 05, 2024',
    imageUrl: 'https://picsum.photos/seed/festival/800/600',
    category: 'Music'
  },
  {
    id: '8',
    slug: 'burna-boy-interview',
    title: 'Burna Boy: Sitting on Top of the World',
    excerpt: 'An opinion piece on the African Giant\'s trajectory and his latest album impact.',
    content: 'He told us...',
    author: 'Michael B.',
    date: 'Jan 10, 2024',
    imageUrl: 'https://picsum.photos/seed/burna/800/600',
    category: 'Music'
  },
  {
    id: '9',
    slug: 'tech-meet-entertainment',
    title: 'How Fintech is Powering the Creative Economy',
    excerpt: 'Startups like Flutterwave and Paystack are becoming the biggest sponsors of entertainment events in West Africa.',
    content: 'Money moves...',
    author: 'Kweku A.',
    date: 'Jan 12, 2024',
    imageUrl: 'https://picsum.photos/seed/fintech/800/600',
    category: 'Industry'
  },
  {
    id: '10',
    slug: 'afrobeats-in-hollywood',
    title: 'Afrobeats Takes Over Hollywood Soundtracks',
    excerpt: 'From Black Panther to blockbuster movies, African music is becoming the soundtrack of choice for filmmakers worldwide.',
    content: 'The sound of Africa is resonating through cinema...',
    author: 'Chioma N.',
    date: 'Jan 18, 2024',
    imageUrl: 'https://picsum.photos/seed/hollywood/800/600',
    category: 'Music',
    featured: true
  },
  {
    id: '11',
    slug: 'south-african-rap-scene',
    title: 'The Rise of South African Hip-Hop',
    excerpt: 'A new generation of rappers is putting South Africa on the global map with their unique blend of local languages and trap beats.',
    content: 'Hip-hop in South Africa has evolved...',
    author: 'Sipho M.',
    date: 'Jan 22, 2024',
    imageUrl: 'https://picsum.photos/seed/sarap/800/600',
    category: 'Music'
  },
  {
    id: '12',
    slug: 'african-fashion-week-paris',
    title: 'African Designers Shine at Paris Fashion Week',
    excerpt: 'Ten African designers showcased their collections, proving that African fashion is not just a trend but a movement.',
    content: 'The runway was filled with vibrant prints...',
    author: 'Zainab A.',
    date: 'Jan 25, 2024',
    imageUrl: 'https://picsum.photos/seed/fashionparis/800/600',
    category: 'Lifestyle'
  },
  {
    id: '13',
    slug: 'streaming-revolution-africa',
    title: 'How Streaming Platforms Are Changing African Music Distribution',
    excerpt: 'Spotify, Apple Music, and Boomplay are democratizing music distribution, giving independent artists unprecedented reach.',
    content: 'The digital revolution has arrived...',
    author: 'Emeka O.',
    date: 'Jan 28, 2024',
    imageUrl: 'https://picsum.photos/seed/streaming/800/600',
    category: 'Industry'
  },
  {
    id: '14',
    slug: 'afrobeats-dance-evolution',
    title: 'The Evolution of Afrobeats Dance Moves',
    excerpt: 'From Shoki to Zanku, we trace the dance moves that defined each era of Afrobeats and their global impact.',
    content: 'Dance and music are inseparable...',
    author: 'David K.',
    date: 'Feb 01, 2024',
    imageUrl: 'https://picsum.photos/seed/danceevo/800/600',
    category: 'Culture',
    featured: true
  },
  {
    id: '15',
    slug: 'grammy-nominations-2024',
    title: 'African Artists Dominate Grammy Nominations',
    excerpt: 'A record-breaking 15 nominations for African artists across multiple categories, signaling a new era of global recognition.',
    content: 'The Grammy nominations are in...',
    author: 'Sarah J.',
    date: 'Feb 05, 2024',
    imageUrl: 'https://picsum.photos/seed/grammy2024/800/600',
    category: 'News'
  },
  {
    id: '16',
    slug: 'nollywood-on-netflix',
    title: 'Nollywood\'s Global Expansion on Streaming Platforms',
    excerpt: 'Nigerian films are finding worldwide audiences on Netflix, with some titles ranking in the top 10 globally.',
    content: 'The Nigerian film industry continues to grow...',
    author: 'Michael B.',
    date: 'Feb 08, 2024',
    imageUrl: 'https://picsum.photos/seed/nollywood/800/600',
    category: 'Industry'
  },
  {
    id: '17',
    slug: 'african-podcast-boom',
    title: 'The African Podcast Boom: Voices That Matter',
    excerpt: 'Podcasts are becoming the new radio, with African creators building massive audiences discussing culture, politics, and entertainment.',
    content: 'Audio content is having a moment...',
    author: 'Kweku A.',
    date: 'Feb 12, 2024',
    imageUrl: 'https://picsum.photos/seed/podcast/800/600',
    category: 'Culture'
  },
  {
    id: '18',
    slug: 'tyla-grammy-win',
    title: 'Tyla Makes History at the Grammys',
    excerpt: 'The South African singer becomes the first African artist to win Best African Music Performance, marking a historic moment.',
    content: 'History was made at the 66th Grammy Awards...',
    author: 'Chioma N.',
    date: 'Feb 15, 2024',
    imageUrl: 'https://picsum.photos/seed/tylagrammy/800/600',
    category: 'News',
    featured: true
  },
  {
    id: '19',
    slug: 'afrobeats-festivals-europe',
    title: 'Afrobeats Festivals Take Over European Summer',
    excerpt: 'Afro Nation, Afrochella, and more festivals are expanding to European cities, bringing the African music experience to new audiences.',
    content: 'Summer 2024 is set to be epic...',
    author: 'Sarah J.',
    date: 'Feb 18, 2024',
    imageUrl: 'https://picsum.photos/seed/festivals/800/600',
    category: 'Music'
  },
  {
    id: '20',
    slug: 'african-hip-hop-legacy',
    title: 'Building a Legacy: African Hip-Hop Pioneers',
    excerpt: 'From Modenine to Sarkodie, we celebrate the artists who paved the way for today\'s African hip-hop stars.',
    content: 'Every generation stands on the shoulders...',
    author: 'Emeka O.',
    date: 'Feb 22, 2024',
    imageUrl: 'https://picsum.photos/seed/hiphoplegacy/800/600',
    category: 'Culture'
  },
  {
    id: '21',
    slug: 'sustainability-in-music',
    title: 'Green Concerts: The Push for Sustainable Music Events',
    excerpt: 'African music festivals are leading the way in eco-friendly practices, from solar-powered stages to zero-waste policies.',
    content: 'The music industry is going green...',
    author: 'Zainab A.',
    date: 'Feb 25, 2024',
    imageUrl: 'https://picsum.photos/seed/green/800/600',
    category: 'Lifestyle'
  },
  {
    id: '22',
    slug: 'women-in-afrobeats',
    title: 'Women Leading the Afrobeats Revolution',
    excerpt: 'Ayra Starr, Tems, Tiwa Savage, and more are proving that the future of Afrobeats is female.',
    content: 'The landscape is shifting...',
    author: 'Chioma N.',
    date: 'Mar 01, 2024',
    imageUrl: 'https://picsum.photos/seed/women/800/600',
    category: 'Music',
    featured: true
  },
  {
    id: '23',
    slug: 'african-art-music-videos',
    title: 'The Artistry Behind African Music Videos',
    excerpt: 'Music videos from the continent are pushing creative boundaries and winning international awards for their storytelling.',
    content: 'Visual storytelling meets music...',
    author: 'David K.',
    date: 'Mar 05, 2024',
    imageUrl: 'https://picsum.photos/seed/musicvideo/800/600',
    category: 'Culture'
  },
  {
    id: '24',
    slug: 'collaboration-culture',
    title: 'Why Collaboration Is King in African Music',
    excerpt: 'The culture of featuring other artists has created some of the biggest hits and strongest friendships in the industry.',
    content: 'Together we rise...',
    author: 'Michael B.',
    date: 'Mar 08, 2024',
    imageUrl: 'https://picsum.photos/seed/collab/800/600',
    category: 'Music'
  },
  {
    id: '25',
    slug: 'afrobeat-vs-afrobeats',
    title: 'Afrobeat vs Afrobeats: Understanding the Difference',
    excerpt: 'A deep dive into the history and evolution of these two distinct but related genres that represent different eras of African music.',
    content: 'The distinction matters...',
    author: 'Sipho M.',
    date: 'Mar 12, 2024',
    imageUrl: 'https://picsum.photos/seed/afrobeat/800/600',
    category: 'Music'
  }
];

export const VIDEOS: Video[] = [
  {
    id: '1',
    title: '100AFRO Vibes: Official Channel Highlight',
    youtubeId: 'Y0zwOpTGq-E',
    thumbnailUrl: 'https://img.youtube.com/vi/Y0zwOpTGq-E/maxresdefault.jpg',
    duration: '03:45',
    views: '15K',
    date: 'Featured',
    category: 'Dance',
    featured: true,
    tags: ['Highlight', 'Official', 'Compilation']
  },
  {
    id: '2',
    title: 'Top 5 Afrobeats Songs This Week',
    youtubeId: 'kJQP7kiw5Fk',
    thumbnailUrl: 'https://picsum.photos/seed/vid2/640/360',
    duration: '08:15',
    views: '540K',
    date: '1 week ago',
    category: 'Music Video',
    tags: ['Afrobeats', 'Charts', 'Nigeria', 'Ghana']
  },
  {
    id: '3',
    title: 'Exclusive Interview with Burna Boy Lookalike',
    youtubeId: '9bZkp7q19f0',
    thumbnailUrl: 'https://picsum.photos/seed/vid3/640/360',
    duration: '15:30',
    views: '2.1M',
    date: '2 weeks ago',
    category: 'Interview',
    featured: true,
    tags: ['Comedy', 'Burna Boy', 'Viral']
  },
  {
    id: '4',
    title: 'How to Cook Jollof Rice (Ghana Style)',
    youtubeId: 'M7lc1UVf-VE',
    thumbnailUrl: 'https://picsum.photos/seed/vid4/640/360',
    duration: '12:00',
    views: '800K',
    date: '3 weeks ago',
    category: 'Vlog',
    tags: ['Food', 'Ghana', 'Jollof', 'Tutorial']
  },
  {
    id: '5',
    title: 'Reaction: Wizkid New Album',
    youtubeId: 'frhPjoW2qSg',
    thumbnailUrl: 'https://picsum.photos/seed/vid5/640/360',
    duration: '09:45',
    views: '300K',
    date: '1 month ago',
    category: 'Vlog',
    tags: ['Review', 'Wizkid', 'Music', 'Reaction']
  },
  {
    id: '6',
    title: 'Amapiano Mix 2024',
    youtubeId: 'lTRiuFIWV54',
    thumbnailUrl: 'https://picsum.photos/seed/vid6/640/360',
    duration: '45:00',
    views: '5M',
    date: '1 month ago',
    category: 'Music Video',
    tags: ['Amapiano', 'South Africa', 'Mix', 'DJ']
  },
   {
    id: '7',
    title: 'Street Food Tour in Nairobi',
    youtubeId: 'ScMzIvxBSi4',
    thumbnailUrl: 'https://picsum.photos/seed/vid7/640/360',
    duration: '14:20',
    views: '600K',
    date: '1 month ago',
    category: 'Vlog',
    tags: ['Food', 'Travel', 'Kenya', 'Nairobi']
  },
  {
    id: '8',
    title: 'Afro Future Festival Highlights',
    youtubeId: '5qap5aO4i9A',
    thumbnailUrl: 'https://picsum.photos/seed/vid8/640/360',
    duration: '04:50',
    views: '120K',
    date: '2 months ago',
    category: 'Performance',
    featured: true,
    tags: ['Festival', 'Live', 'Concert']
  },
  {
    id: '9',
    title: 'Traditional Wedding Entrance Dance',
    youtubeId: 'OPf0YbXqDm0',
    thumbnailUrl: 'https://picsum.photos/seed/vid9/640/360',
    duration: '03:10',
    views: '4.5M',
    date: '2 months ago',
    category: 'Dance',
    tags: ['Wedding', 'Culture', 'Viral', 'Dance']
  },
  {
    id: '10',
    title: 'Comedy Skit: African Mothers',
    youtubeId: 'C0DPdy98e4c',
    thumbnailUrl: 'https://picsum.photos/seed/vid10/640/360',
    duration: '02:45',
    views: '8M',
    date: '3 months ago',
    category: 'Vlog',
    tags: ['Comedy', 'Skit', 'Relatable']
  },
  {
    id: '11',
    title: 'Behind The Scenes: Music Video Shoot',
    youtubeId: 'jNQXAC9IVRw',
    thumbnailUrl: 'https://picsum.photos/seed/vid11/640/360',
    duration: '11:10',
    views: '200K',
    date: '3 months ago',
    category: 'Interview',
    tags: ['BTS', 'Music', 'Production']
  },
  {
    id: '12',
    title: 'Learning Swahili in 24 Hours',
    youtubeId: 'JGwWNGJdvx8',
    thumbnailUrl: 'https://picsum.photos/seed/vid12/640/360',
    duration: '18:00',
    views: '150K',
    date: '4 months ago',
    category: 'Vlog',
    tags: ['Language', 'Education', 'Challenge']
  },
  {
    id: '13',
    title: 'Davido Concert Live London',
    youtubeId: 'JGwWNGJdvx8',
    thumbnailUrl: 'https://picsum.photos/seed/vid13/640/360',
    duration: '01:20:00',
    views: '10M',
    date: '5 months ago',
    category: 'Performance',
    tags: ['Davido', 'Live', 'Concert', 'London']
  },
    {
    id: '14',
    title: 'Rema - Calm Down (Live)',
    youtubeId: 'JGwWNGJdvx8',
    thumbnailUrl: 'https://picsum.photos/seed/vid14/640/360',
    duration: '04:00',
    views: '50M',
    date: '6 months ago',
    category: 'Performance',
    tags: ['Rema', 'Live', 'Global']
  },
  {
    id: '15',
    title: 'Asake - Work of Art Album Review',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnailUrl: 'https://picsum.photos/seed/vid15/640/360',
    duration: '22:30',
    views: '180K',
    date: '3 weeks ago',
    category: 'Interview',
    tags: ['Asake', 'Review', 'Album']
  },
  {
    id: '16',
    title: 'Ayra Starr - Rush (Official Video)',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnailUrl: 'https://picsum.photos/seed/vid16/640/360',
    duration: '03:30',
    views: '12M',
    date: '2 months ago',
    category: 'Music Video',
    featured: true,
    tags: ['Ayra Starr', 'Music Video', 'Official']
  },
  {
    id: '17',
    title: 'Amapiano Dance Challenge Compilation',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnailUrl: 'https://picsum.photos/seed/vid17/640/360',
    duration: '15:45',
    views: '3.2M',
    date: '1 month ago',
    category: 'Dance',
    tags: ['Amapiano', 'Challenge', 'Dance']
  },
  {
    id: '18',
    title: 'Tems - Free Mind (Live Performance)',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnailUrl: 'https://picsum.photos/seed/vid18/640/360',
    duration: '04:15',
    views: '8.5M',
    date: '4 months ago',
    category: 'Performance',
    tags: ['Tems', 'Live', 'Performance']
  },
  {
    id: '19',
    title: 'Fireboy DML Interview: Journey to Success',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnailUrl: 'https://picsum.photos/seed/vid19/640/360',
    duration: '28:20',
    views: '450K',
    date: '2 weeks ago',
    category: 'Interview',
    tags: ['Fireboy DML', 'Interview', 'Success']
  },
  {
    id: '20',
    title: 'Top 20 Afrobeats Songs 2024',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnailUrl: 'https://picsum.photos/seed/vid20/640/360',
    duration: '12:00',
    views: '2.8M',
    date: '1 week ago',
    category: 'Music Video',
    tags: ['Top 20', 'Afrobeats', '2024']
  },
  {
    id: '21',
    title: 'Nigerian Street Food: Taste Test',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnailUrl: 'https://picsum.photos/seed/vid21/640/360',
    duration: '16:30',
    views: '950K',
    date: '3 weeks ago',
    category: 'Vlog',
    tags: ['Food', 'Nigeria', 'Street Food']
  },
  {
    id: '22',
    title: 'Burna Boy - City Boys (Official Video)',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnailUrl: 'https://picsum.photos/seed/vid22/640/360',
    duration: '04:00',
    views: '25M',
    date: '3 months ago',
    category: 'Music Video',
    featured: true,
    tags: ['Burna Boy', 'Music Video', 'Official']
  },
  {
    id: '23',
    title: 'Wizkid Concert Highlights London',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnailUrl: 'https://picsum.photos/seed/vid23/640/360',
    duration: '08:45',
    views: '1.5M',
    date: '1 month ago',
    category: 'Performance',
    tags: ['Wizkid', 'Concert', 'London']
  },
  {
    id: '24',
    title: 'DJ Maphorisa Amapiano Mix 2024',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnailUrl: 'https://picsum.photos/seed/vid24/640/360',
    duration: '60:00',
    views: '5.8M',
    date: '2 months ago',
    category: 'Music Video',
    tags: ['DJ Maphorisa', 'Amapiano', 'Mix']
  },
  {
    id: '25',
    title: 'Libianca - People (Reaction Video)',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnailUrl: 'https://picsum.photos/seed/vid25/640/360',
    duration: '06:20',
    views: '320K',
    date: '2 weeks ago',
    category: 'Vlog',
    tags: ['Libianca', 'Reaction', 'People']
  },
  {
    id: '26',
    title: 'Afro Nation Festival Vlog 2024',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnailUrl: 'https://picsum.photos/seed/vid26/640/360',
    duration: '18:15',
    views: '720K',
    date: '1 month ago',
    category: 'Vlog',
    featured: true,
    tags: ['Afro Nation', 'Festival', 'Vlog']
  },
  {
    id: '27',
    title: 'Rema - Soundgasm (Live Performance)',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnailUrl: 'https://picsum.photos/seed/vid27/640/360',
    duration: '03:45',
    views: '4.2M',
    date: '3 months ago',
    category: 'Performance',
    tags: ['Rema', 'Live', 'Soundgasm']
  },
  {
    id: '28',
    title: 'African Dance Moves Tutorial',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnailUrl: 'https://picsum.photos/seed/vid28/640/360',
    duration: '10:30',
    views: '1.8M',
    date: '2 months ago',
    category: 'Dance',
    tags: ['Dance', 'Tutorial', 'African']
  },
  {
    id: '29',
    title: 'Davido - Unavailable (Official Video)',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnailUrl: 'https://picsum.photos/seed/vid29/640/360',
    duration: '04:10',
    views: '18M',
    date: '4 months ago',
    category: 'Music Video',
    tags: ['Davido', 'Music Video', 'Official']
  },
  {
    id: '30',
    title: 'Omah Lay - Boy Alone Album Review',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnailUrl: 'https://picsum.photos/seed/vid30/640/360',
    duration: '25:00',
    views: '280K',
    date: '3 weeks ago',
    category: 'Interview',
    tags: ['Omah Lay', 'Review', 'Album']
  }
];

// Sample audio link for demo purposes
const DEMO_AUDIO = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3";

export const CHART_DATA: { songs: ChartEntry[], albums: ChartEntry[] } = {
  songs: [
    { 
      rank: 1, 
      title: 'Water', 
      artist: 'Tyla', 
      coverUrl: 'https://picsum.photos/seed/tyla/300', 
      trend: 'same', 
      lastWeek: 1, 
      peak: 1, 
      weeksOnChart: 12,
      previewUrl: DEMO_AUDIO,
      externalLinks: { spotify: '#', appleMusic: '#' }
    },
    { 
      rank: 2, 
      title: 'City Boys', 
      artist: 'Burna Boy', 
      coverUrl: 'https://picsum.photos/seed/burna2/300', 
      trend: 'up', 
      lastWeek: 4, 
      peak: 2, 
      weeksOnChart: 8,
      previewUrl: DEMO_AUDIO,
      externalLinks: { spotify: '#', appleMusic: '#' }
    },
    { 
      rank: 3, 
      title: 'Unavailable', 
      artist: 'Davido ft. Musa Keys', 
      coverUrl: 'https://picsum.photos/seed/davido2/300', 
      trend: 'down', 
      lastWeek: 2, 
      peak: 1, 
      weeksOnChart: 24,
      previewUrl: DEMO_AUDIO,
      externalLinks: { spotify: '#' }
    },
    { 
      rank: 4, 
      title: 'Me & U', 
      artist: 'Tems', 
      coverUrl: 'https://picsum.photos/seed/tems/300', 
      trend: 'same', 
      lastWeek: 4, 
      peak: 4, 
      weeksOnChart: 6,
      previewUrl: DEMO_AUDIO,
      externalLinks: { spotify: '#', appleMusic: '#' }
    },
    { 
      rank: 5, 
      title: 'Lonely At The Top', 
      artist: 'Asake', 
      coverUrl: 'https://picsum.photos/seed/asake/300', 
      trend: 'down', 
      lastWeek: 3, 
      peak: 1, 
      weeksOnChart: 16,
      previewUrl: DEMO_AUDIO,
      externalLinks: { appleMusic: '#' }
    },
    { rank: 6, title: 'Calm Down', artist: 'Rema', coverUrl: 'https://picsum.photos/seed/rema/300', trend: 'same', lastWeek: 6, peak: 1, weeksOnChart: 52, previewUrl: DEMO_AUDIO, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 7, title: 'Terminator', artist: 'King Promise', coverUrl: 'https://picsum.photos/seed/kingpromise/300', trend: 'up', lastWeek: 9, peak: 7, weeksOnChart: 5, previewUrl: DEMO_AUDIO, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 8, title: 'Cast', artist: 'Shallipopi', coverUrl: 'https://picsum.photos/seed/shalli/300', trend: 'new', lastWeek: null, peak: 8, weeksOnChart: 1, previewUrl: DEMO_AUDIO, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 9, title: 'Amapiano', artist: 'Asake ft. Olamide', coverUrl: 'https://picsum.photos/seed/asake2/300', trend: 'down', lastWeek: 7, peak: 2, weeksOnChart: 20, previewUrl: DEMO_AUDIO, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 10, title: 'Sittin\' on Top of the World', artist: 'Burna Boy', coverUrl: 'https://picsum.photos/seed/burna3/300', trend: 'down', lastWeek: 8, peak: 3, weeksOnChart: 14, previewUrl: DEMO_AUDIO, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 11, title: 'People', artist: 'Libianca', coverUrl: 'https://picsum.photos/seed/libianca/300', trend: 'up', lastWeek: 15, peak: 11, weeksOnChart: 8, previewUrl: DEMO_AUDIO, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 12, title: 'Rush', artist: 'Ayra Starr', coverUrl: 'https://picsum.photos/seed/ayra/300', trend: 'same', lastWeek: 12, peak: 5, weeksOnChart: 18, previewUrl: DEMO_AUDIO, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 13, title: 'Last Last', artist: 'Burna Boy', coverUrl: 'https://picsum.photos/seed/lastlast/300', trend: 'down', lastWeek: 11, peak: 1, weeksOnChart: 45, previewUrl: DEMO_AUDIO, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 14, title: 'Essence', artist: 'Wizkid ft. Tems', coverUrl: 'https://picsum.photos/seed/essence/300', trend: 'same', lastWeek: 14, peak: 1, weeksOnChart: 78, previewUrl: DEMO_AUDIO, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 15, title: 'Love Nwantiti', artist: 'CKay', coverUrl: 'https://picsum.photos/seed/ckay/300', trend: 'down', lastWeek: 13, peak: 1, weeksOnChart: 92, previewUrl: DEMO_AUDIO, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 16, title: 'Peru', artist: 'Fireboy DML & Ed Sheeran', coverUrl: 'https://picsum.photos/seed/peru/300', trend: 'up', lastWeek: 18, peak: 2, weeksOnChart: 56, previewUrl: DEMO_AUDIO, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 17, title: 'KU LO SA', artist: 'Oxlade', coverUrl: 'https://picsum.photos/seed/oxlade/300', trend: 'new', lastWeek: null, peak: 17, weeksOnChart: 1, previewUrl: DEMO_AUDIO, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 18, title: 'Soweto', artist: 'Victony, Tempoe & Don Toliver', coverUrl: 'https://picsum.photos/seed/soweto/300', trend: 'up', lastWeek: 20, peak: 6, weeksOnChart: 32, previewUrl: DEMO_AUDIO, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 19, title: 'Overloading', artist: 'Mavins, Crayon, Ayra Starr, LADIPOE, Magixx, Boy Spyce', coverUrl: 'https://picsum.photos/seed/overloading/300', trend: 'down', lastWeek: 16, peak: 10, weeksOnChart: 12, previewUrl: DEMO_AUDIO, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 20, title: 'Asiwaju', artist: 'Ruger', coverUrl: 'https://picsum.photos/seed/ruger/300', trend: 'same', lastWeek: 19, peak: 8, weeksOnChart: 28, previewUrl: DEMO_AUDIO, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 21, title: 'Bandana', artist: 'Asake ft. Fireboy DML', coverUrl: 'https://picsum.photos/seed/bandana/300', trend: 'down', lastWeek: 17, peak: 4, weeksOnChart: 26, previewUrl: DEMO_AUDIO, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 22, title: 'Stamina', artist: 'Tiwa Savage, Ayra Starr, Young Jonn', coverUrl: 'https://picsum.photos/seed/stamina/300', trend: 'up', lastWeek: 23, peak: 12, weeksOnChart: 14, previewUrl: DEMO_AUDIO, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 23, title: 'Xtra Cool', artist: 'Young Jonn', coverUrl: 'https://picsum.photos/seed/xtracool/300', trend: 'new', lastWeek: null, peak: 23, weeksOnChart: 1, previewUrl: DEMO_AUDIO, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 24, title: 'Soundgasm', artist: 'Rema', coverUrl: 'https://picsum.photos/seed/soundgasm/300', trend: 'down', lastWeek: 21, peak: 7, weeksOnChart: 19, previewUrl: DEMO_AUDIO, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 25, title: 'Dollar', artist: 'Tyler ICU, DJ Maphorisa, Nandipha808, Ceeka RSA, Tyron Dee', coverUrl: 'https://picsum.photos/seed/dollar/300', trend: 'same', lastWeek: 24, peak: 15, weeksOnChart: 22, previewUrl: DEMO_AUDIO, externalLinks: { spotify: '#', appleMusic: '#' } },
  ],
  albums: [
    { rank: 1, title: 'I Told Them...', artist: 'Burna Boy', coverUrl: 'https://picsum.photos/seed/itoldthem/300', trend: 'same', lastWeek: 1, peak: 1, weeksOnChart: 15, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 2, title: 'Timeless', artist: 'Davido', coverUrl: 'https://picsum.photos/seed/timeless/300', trend: 'same', lastWeek: 2, peak: 1, weeksOnChart: 30, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 3, title: 'Work of Art', artist: 'Asake', coverUrl: 'https://picsum.photos/seed/workofart/300', trend: 'up', lastWeek: 4, peak: 2, weeksOnChart: 22, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 4, title: 'Rave & Roses Ultra', artist: 'Rema', coverUrl: 'https://picsum.photos/seed/rave/300', trend: 'down', lastWeek: 3, peak: 1, weeksOnChart: 60, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 5, title: 'Thy Kingdom Come', artist: 'Seyi Vibez', coverUrl: 'https://picsum.photos/seed/seyi/300', trend: 'new', lastWeek: null, peak: 5, weeksOnChart: 1, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 6, title: 'More Love, Less Ego', artist: 'Wizkid', coverUrl: 'https://picsum.photos/seed/morelove/300', trend: 'same', lastWeek: 6, peak: 1, weeksOnChart: 48, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 7, title: '19 & Dangerous', artist: 'Ayra Starr', coverUrl: 'https://picsum.photos/seed/19dangerous/300', trend: 'up', lastWeek: 9, peak: 3, weeksOnChart: 36, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 8, title: 'Mr. Money With The Vibe', artist: 'Asake', coverUrl: 'https://picsum.photos/seed/mrmoney/300', trend: 'down', lastWeek: 7, peak: 2, weeksOnChart: 42, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 9, title: 'Boy Alone', artist: 'Omah Lay', coverUrl: 'https://picsum.photos/seed/boyalone/300', trend: 'same', lastWeek: 8, peak: 4, weeksOnChart: 28, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 10, title: 'Water & Garri', artist: 'Tems', coverUrl: 'https://picsum.photos/seed/watergarri/300', trend: 'up', lastWeek: 12, peak: 5, weeksOnChart: 20, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 11, title: 'DND', artist: 'Ruger', coverUrl: 'https://picsum.photos/seed/dnd/300', trend: 'new', lastWeek: null, peak: 11, weeksOnChart: 1, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 12, title: 'Alpha', artist: 'Omah Lay', coverUrl: 'https://picsum.photos/seed/alpha/300', trend: 'down', lastWeek: 10, peak: 6, weeksOnChart: 24, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 13, title: 'Love, Damini', artist: 'Burna Boy', coverUrl: 'https://picsum.photos/seed/lovedamini/300', trend: 'same', lastWeek: 13, peak: 1, weeksOnChart: 72, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 14, title: 'Made in Lagos', artist: 'Wizkid', coverUrl: 'https://picsum.photos/seed/madeinlagos/300', trend: 'same', lastWeek: 14, peak: 1, weeksOnChart: 96, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 15, title: 'African Giant', artist: 'Burna Boy', coverUrl: 'https://picsum.photos/seed/africangiant/300', trend: 'down', lastWeek: 11, peak: 2, weeksOnChart: 88, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 16, title: 'Twice As Tall', artist: 'Burna Boy', coverUrl: 'https://picsum.photos/seed/twiceastall/300', trend: 'same', lastWeek: 15, peak: 1, weeksOnChart: 104, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 17, title: 'A Better Time', artist: 'Davido', coverUrl: 'https://picsum.photos/seed/bettertime/300', trend: 'up', lastWeek: 18, peak: 3, weeksOnChart: 54, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 18, title: 'Outside', artist: 'Burna Boy', coverUrl: 'https://picsum.photos/seed/outside/300', trend: 'down', lastWeek: 16, peak: 4, weeksOnChart: 66, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 19, title: 'Omo X 100', artist: 'Rema', coverUrl: 'https://picsum.photos/seed/omox100/300', trend: 'new', lastWeek: null, peak: 19, weeksOnChart: 1, externalLinks: { spotify: '#', appleMusic: '#' } },
    { rank: 20, title: 'Patoranking', artist: 'Patoranking', coverUrl: 'https://picsum.photos/seed/patoranking/300', trend: 'same', lastWeek: 19, peak: 8, weeksOnChart: 32, externalLinks: { spotify: '#', appleMusic: '#' } },
  ]
};

export const COMMENTS: Comment[] = [
  { id: 'c1', postId: '1', author: 'Kwame', content: 'Great article! The stats on Burna Boy are incredible.', date: '2 hours ago', likes: 12 },
  { id: 'c2', postId: '1', author: 'Nia', content: 'Afrobeats to the world! 🌍', date: '5 hours ago', likes: 45 },
  { id: 'c3', postId: '1', author: 'John Doe', content: 'I wish you covered more East African artists though.', date: '1 day ago', likes: 3 },
  { id: 'c4', postId: '3', author: 'DJ Maphorisa fan', content: 'Amapiano is a lifestyle, not just a genre.', date: '30 mins ago', likes: 8 },
  { id: 'c5', postId: '2', author: 'Amina', content: 'Shoki dance move was everything in 2015! Great memories.', date: '3 hours ago', likes: 15 },
  { id: 'c6', postId: '3', author: 'Thabo', content: 'South Africa to the world! 🇿🇦 Amapiano is taking over.', date: '1 hour ago', likes: 32 },
  { id: 'c7', postId: '4', author: 'Fashionista', content: 'Lagos Fashion Week never disappoints. The designs were stunning!', date: '6 hours ago', likes: 24 },
  { id: 'c8', postId: '5', author: 'Music Biz', content: 'This is huge for independent artists. The industry is changing.', date: '1 day ago', likes: 18 },
  { id: 'c9', postId: '6', author: 'Data Analyst', content: 'The growth is exponential! Excited to see what 2024 brings.', date: '2 days ago', likes: 9 },
  { id: 'c10', postId: '7', author: 'Festival Goer', content: 'I was there last year! Best experience of my life. Can\'t wait!', date: '4 hours ago', likes: 41 },
  { id: 'c11', postId: '8', author: 'Burna Fan', content: 'Burna Boy is a legend. His music speaks to the soul.', date: '8 hours ago', likes: 67 },
  { id: 'c12', postId: '9', author: 'Tech Enthusiast', content: 'Fintech + Entertainment = The future. Great analysis!', date: '12 hours ago', likes: 22 },
  { id: 'c13', postId: '10', author: 'Movie Lover', content: 'I noticed this too! So many African songs in movies lately. Love it!', date: '1 day ago', likes: 29 },
  { id: 'c14', postId: '11', author: 'Hip-Hop Head', content: 'South African rap is underrated. They have incredible talent!', date: '2 days ago', likes: 16 },
  { id: 'c15', postId: '12', author: 'Fashion Designer', content: 'Representation matters. So proud of our designers!', date: '5 hours ago', likes: 38 },
  { id: 'c16', postId: '13', author: 'Artist', content: 'Streaming changed my life. I can reach fans worldwide now.', date: '1 day ago', likes: 51 },
  { id: 'c17', postId: '14', author: 'Dancer', content: 'Zanku changed everything! Dance moves keep evolving.', date: '3 hours ago', likes: 43 },
  { id: 'c18', postId: '15', author: 'Award Watcher', content: 'So well deserved! African music is finally getting recognition.', date: '6 hours ago', likes: 74 },
  { id: 'c19', postId: '16', author: 'Nollywood Fan', content: 'Nigerian movies are so good! Netflix is smart to invest.', date: '1 day ago', likes: 27 },
  { id: 'c20', postId: '18', author: 'Tyla Stan', content: 'She made history! So proud of her achievement.', date: '4 hours ago', likes: 89 },
  { id: 'c21', postId: '20', author: 'Music Historian', content: 'Great breakdown of the genre differences. Very educational!', date: '2 days ago', likes: 14 },
  { id: 'c22', postId: '22', author: 'Women Supporter', content: 'These women are killing it! The future is female! 💪', date: '8 hours ago', likes: 96 },
  { id: 'c23', postId: '24', author: 'Collaboration Lover', content: 'The best songs come from collaborations. Unity is strength!', date: '1 day ago', likes: 33 },
];

export const FEATURED_ARTISTS: Artist[] = [
  { id: '1', name: 'Burna Boy', imageUrl: 'https://ui-avatars.com/api/?name=Burna+Boy&background=166534&color=fff&size=200', genre: 'Afro-Fusion', socialLink: '#' },
  { id: '2', name: 'Tyla', imageUrl: 'https://ui-avatars.com/api/?name=Tyla&background=F59E0B&color=000&size=200', genre: 'Amapiano/Pop', socialLink: '#' },
  { id: '3', name: 'Davido', imageUrl: 'https://ui-avatars.com/api/?name=Davido&background=111827&color=fff&size=200', genre: 'Afrobeats', socialLink: '#' },
  { id: '4', name: 'Ayra Starr', imageUrl: 'https://ui-avatars.com/api/?name=Ayra+Starr&background=EF4444&color=fff&size=200', genre: 'Afropop', socialLink: '#' },
  { id: '5', name: 'Rema', imageUrl: 'https://ui-avatars.com/api/?name=Rema&background=8B5CF6&color=fff&size=200', genre: 'Afrorave', socialLink: '#' },
  { id: '6', name: 'Wizkid', imageUrl: 'https://ui-avatars.com/api/?name=Wizkid&background=10B981&color=fff&size=200', genre: 'Afrobeats', socialLink: '#' },
  { id: '7', name: 'Asake', imageUrl: 'https://ui-avatars.com/api/?name=Asake&background=DC2626&color=fff&size=200', genre: 'Afrobeats', socialLink: '#' },
  { id: '8', name: 'Tems', imageUrl: 'https://ui-avatars.com/api/?name=Tems&background=7C3AED&color=fff&size=200', genre: 'R&B/Afrobeats', socialLink: '#' },
  { id: '9', name: 'Omah Lay', imageUrl: 'https://ui-avatars.com/api/?name=Omah+Lay&background=059669&color=fff&size=200', genre: 'Afrobeats', socialLink: '#' },
  { id: '10', name: 'Fireboy DML', imageUrl: 'https://ui-avatars.com/api/?name=Fireboy+DML&background=EA580C&color=fff&size=200', genre: 'Afropop', socialLink: '#' },
  { id: '11', name: 'Libianca', imageUrl: 'https://ui-avatars.com/api/?name=Libianca&background=0891B2&color=fff&size=200', genre: 'Afropop', socialLink: '#' },
  { id: '12', name: 'CKay', imageUrl: 'https://ui-avatars.com/api/?name=CKay&background=BE185D&color=fff&size=200', genre: 'Afrobeats', socialLink: '#' },
  { id: '13', name: 'Tiwa Savage', imageUrl: 'https://ui-avatars.com/api/?name=Tiwa+Savage&background=F59E0B&color=000&size=200', genre: 'Afropop', socialLink: '#' },
  { id: '14', name: 'Oxlade', imageUrl: 'https://ui-avatars.com/api/?name=Oxlade&background=1E40AF&color=fff&size=200', genre: 'Afrobeats', socialLink: '#' },
  { id: '15', name: 'Victony', imageUrl: 'https://ui-avatars.com/api/?name=Victony&background=7C2D12&color=fff&size=200', genre: 'Afrobeats', socialLink: '#' },
  { id: '16', name: 'Ruger', imageUrl: 'https://ui-avatars.com/api/?name=Ruger&background=065F46&color=fff&size=200', genre: 'Afrobeats', socialLink: '#' },
  { id: '17', name: 'Seyi Vibez', imageUrl: 'https://ui-avatars.com/api/?name=Seyi+Vibez&background=991B1B&color=fff&size=200', genre: 'Afrobeats', socialLink: '#' },
  { id: '18', name: 'Young Jonn', imageUrl: 'https://ui-avatars.com/api/?name=Young+Jonn&background=4C1D95&color=fff&size=200', genre: 'Afrobeats', socialLink: '#' },
  { id: '19', name: 'Shallipopi', imageUrl: 'https://ui-avatars.com/api/?name=Shallipopi&background=155E75&color=fff&size=200', genre: 'Afrobeats', socialLink: '#' },
  { id: '20', name: 'King Promise', imageUrl: 'https://ui-avatars.com/api/?name=King+Promise&background=B45309&color=fff&size=200', genre: 'Afrobeats', socialLink: '#' },
  { id: '21', name: 'DJ Maphorisa', imageUrl: 'https://ui-avatars.com/api/?name=DJ+Maphorisa&background=134E4A&color=fff&size=200', genre: 'Amapiano', socialLink: '#' },
  { id: '22', name: 'Kabza De Small', imageUrl: 'https://ui-avatars.com/api/?name=Kabza+De+Small&background=701A75&color=fff&size=200', genre: 'Amapiano', socialLink: '#' },
];

export const TRENDING_TOPICS: TrendingTopic[] = [
  { id: '1', name: 'Detty December', count: '125K Posts', imageUrl: 'https://picsum.photos/seed/detty/400/200' },
  { id: '2', name: 'Grammy 2024', count: '89K Posts', imageUrl: 'https://picsum.photos/seed/grammy/400/200' },
  { id: '3', name: 'Davido vs Wizkid', count: '500K Posts', imageUrl: 'https://picsum.photos/seed/rivalry/400/200' },
  { id: '4', name: 'AfroNation', count: '45K Posts', imageUrl: 'https://picsum.photos/seed/afronation/400/200' },
  { id: '5', name: 'BBNaija', count: '2M Posts', imageUrl: 'https://picsum.photos/seed/bbnaija/400/200' },
  { id: '6', name: 'Tyla Grammy Win', count: '320K Posts', imageUrl: 'https://picsum.photos/seed/tylawin/400/200' },
  { id: '7', name: 'Afrobeats Festival', count: '78K Posts', imageUrl: 'https://picsum.photos/seed/festival/400/200' },
  { id: '8', name: 'Amapiano Worldwide', count: '156K Posts', imageUrl: 'https://picsum.photos/seed/amapiano/400/200' },
  { id: '9', name: 'Nigerian Music Industry', count: '94K Posts', imageUrl: 'https://picsum.photos/seed/naija/400/200' },
  { id: '10', name: 'African Fashion Week', count: '67K Posts', imageUrl: 'https://picsum.photos/seed/fashionweek/400/200' },
  { id: '11', name: 'Burna Boy Tour', count: '112K Posts', imageUrl: 'https://picsum.photos/seed/burnatour/400/200' },
  { id: '12', name: 'Wizkid New Album', count: '245K Posts', imageUrl: 'https://picsum.photos/seed/wizkid/400/200' },
  { id: '13', name: 'Davido Timeless', count: '189K Posts', imageUrl: 'https://picsum.photos/seed/davido/400/200' },
  { id: '14', name: 'Rema Calm Down', count: '423K Posts', imageUrl: 'https://picsum.photos/seed/rema/400/200' },
  { id: '15', name: 'African Music Awards', count: '98K Posts', imageUrl: 'https://picsum.photos/seed/awards/400/200' },
];

export const CURRENT_POLL: Poll = {
  id: 'poll-1',
  question: 'Who should win Artist of the Year?',
  options: [
    { id: 'opt1', text: 'Burna Boy', votes: 1240 },
    { id: 'opt2', text: 'Davido', votes: 1150 },
    { id: 'opt3', text: 'Rema', votes: 890 },
    { id: 'opt4', text: 'Asake', votes: 1050 },
  ]
};

export const ON_THIS_DAY = {
  year: '2012',
  event: 'Oliver Twist by D\'banj enters the UK Top 10 Charts, marking a pivotal moment for Afrobeats global crossover.'
};